version: '3.8'

services:
  # Django Backend Service
  backend:
    build: ./cctv_manager/backend
    container_name: cctv_backend
    volumes:
      - backend_media:/app/media
      - backend_static:/app/static
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-xcf62=o(vt-uud5dc6@!l&nc+&fv&n1j3i8x_yu)mp0q4!yoz@
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - HLS_BASE_URL=http://rtmp_server:8080/hls
      - STATIC_URL=/static/
    ports:
      - "8000:8000"  # Expose Django API directly
    depends_on:
      - rtmp_server
    restart: unless-stopped
    networks:
      - cctv_network

  # Vue.js Frontend Service
  frontend:
    build: ./cctv_manager/frontend
    container_name: cctv_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cctv_network

  # Nginx RTMP Server
  rtmp_server:
    build: ./nginx
    container_name: cctv_rtmp
    restart: unless-stopped
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HTTP for HLS
    volumes:
      - hls_data:/tmp/hls
    networks:
      - cctv_network
      
  # Nginx Static Files Server
  nginx-static:
    image: nginx:alpine
    container_name: cctv_static
    restart: unless-stopped
    volumes:
      - backend_static:/usr/share/nginx/html/static:ro
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    networks:
      - cctv_network

volumes:
  backend_media:
  backend_static:
  hls_data:

networks:
  cctv_network:
    driver: bridge 