# Generated by Django 5.1.7 on 2025-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='rtsp_port',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='stream_path',
        ),
        migrations.AddField(
            model_name='camera',
            name='app_name',
            field=models.CharField(default='live', max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtmp_port',
            field=models.IntegerField(default=1935),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_id',
            field=models.CharField(default='stream1', max_length=255),
        ),
    ]
